version: '3'

services:

  registry:
    image: registry:2
    container_name: registry
    ports:
      - 5000:5000
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
      - REGISTRY_STORAGE_DELETE_ENABLED=true

    volumes:
      - /data:/data
