---
- hosts: all
  become: true
  tasks:

  - name: Install containerd- Create conf file for containerd modules
    copy:
      dest: "/etc/modules-load.d/containerd.conf"
      content: |
        overlay
        br_netfilter

  - name: Install containerd- Load modules
    shell: |
      modprobe overlay
      modprobe br_netfilter

  - name: Install containerd- Setup required sysctl params, these persist across reboots
    copy:
      dest: "/etc/sysctl.d/99-kubernetes-cri.conf"
      content: |
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1

  - name: Install containerd- Apply sysctl params without reboot
    shell: |
      sysctl --system

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name:  Install containerd package
    apt:
      name: containerd
      state: present

  - name: Create containerd configuration directory
    file:
      path: /etc/containerd
      state: directory

  - name: Creating containerd config file
    file:
      path: "/etc/containerd/config.toml"
      state: touch

  - name: Redirect output of containerd config command
    shell: containerd config default > "/etc/containerd/config.toml"

  - name: Restart containerd
    systemd:
      name: containerd
      state: restarted

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet
        - kubeadm
        - kubectl

  - name: Force kubelet to listen on host network IP
    copy:
      dest: "/etc/default/kubelet"
      content: |
        KUBELET_EXTRA_ARGS=--node-ip="{{ node_ip }}"

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Initialize the Kubernetes cluster using kubeadm and use calico as CNI.
    command: kubeadm init --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}"  --node-name "{{ hostname }}" --pod-network-cidr=192.168.0.0/16
    args:
      creates: "/etc/kubernetes/manifests/*yaml"

  - name: Setup kubeconfig - create directory for config file
    file:
      path: /home/vagrant/.kube
      state: directory
      mode: '0755'

  - name: Setup kubeconfig - copy initial kubeconfig file
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/vagrant/.kube/config
      remote_src: yes

  - name: Setup kubeconfig - change file ownership, group and permissions
    file:
      path: /home/vagrant/.kube/config
      owner: vagrant
      group: vagrant
      mode: '0644'

  - name: Install calico pod network
    become: false
    shell: kubectl apply -f "{{ calico_url }}"

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
    become: false

  - name: Download crictl
    get_url:
      url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ crictl_version }}/crictl-v{{ crictl_version }}-linux-amd64.tar.gz"
      dest: /tmp
    tags: crictl

  - name: Create crictl configuration directory
    file:
      path: /etc/crictl
      state: directory
    tags: crictl

  - name: Creating crictl config file
    file:
      path: "/etc/crictl/crictl.yaml"
      state: touch
    tags: crictl

  - name: Populate crictl config file
    copy:
      dest: "/etc/crictl/crictl.yaml"
      content: |
        runtime-endpoint: unix:///run/containerd/containerd.sock
        image-endpoint: unix:///run/containerd/containerd.sock
        timeout: 10
        debug: true
    tags: crictl

  - name: Extract crictl tar into /usr/local/bin
    unarchive:
      src: "/tmp/crictl-v{{ crictl_version }}-linux-amd64.tar.gz"
      dest: /usr/local/bin
      mode: 0755
      remote_src: yes
    tags: crictl

  - name: Set environment variables for crictl command endpoints
    blockinfile: |
      dest=/home/vagrant/.profile backup=yes
      content="export IMAGE_SERVICE_ENDPOINT=unix:///run/containerd/containerd.sock
      export CONTAINER_RUNTIME_ENDPOINT=unix:///run/containerd/containerd.sock"
    tags: crictl

  - name: Source ~/.profile file to shell
    shell: bash -c 'source /home/vagrant/.profile'
    tags: crictl
